export const cardListLeft = [
  {
    category: "fruit",
    name: "Lemons",
    imageSrc: "/icons/lemon.png",
    imageAlt: "lemon",
    number: 0,
  },
  {
    category: "fruit",
    name: "Oranges",
    imageSrc: "/icons/orange.png",
    imageAlt: "oranges",
    number: 1,
  },
  {
    category: "fruit",
    name: "Apples",
    imageSrc: "/icons/apples.png",
    imageAlt: "apples",
    number: 2,
  },
  {
    category: "fruit",
    name: "Avocados",
    imageSrc: "/icons/avocado.png",
    imageAlt: "avocados",
    number: 3,
  },
  {
    category: "fruit",
    name: "Bananas",
    imageSrc: "/icons/banana.png",
    imageAlt: "bananas",
    number: 4,
  },
  {
    category: "grain",
    name: "Bread",
    imageSrc: "/icons/bread.png",
    imageAlt: "bread",
    number: 5,
  },
  {
    category: "grain",
    name: "Cornflakes",
    imageSrc: "/icons/cereal.png",
    imageAlt: "cornflakes",
    number: 6,
  },
  {
    category: "grain",
    name: "Crackers",
    imageSrc: "/icons/crackers.png",
    imageAlt: "crackers",
    number: 7,
  },
  {
    category: "grain",
    name: "Plain Flour",
    imageSrc: "/icons/flour.png",
    imageAlt: "plain flour",
    number: 8,
  },
  {
    category: "grain",
    name: "Whole Wheat Flour",
    imageSrc: "/icons/flour.png",
    imageAlt: "whole wheat flour",
    number: 9,
  },
  {
    category: "proteins",
    name: "Tofu",
    imageSrc: "/icons/tofu.png",
    imageAlt: "tofu",
    number: 10,
  },
  {
    category: "proteins",
    name: "Beef",
    imageSrc: "/icons/beef.png",
    imageAlt: "beef",
    number: 11,
  },
  {
    category: "proteins",
    name: "Cheese",
    imageSrc: "/icons/cheese.png",
    imageAlt: "cheese",
    number: 12,
  },
  {
    category: "proteins",
    name: "Eggs",
    imageSrc: "/icons/eggs.png",
    imageAlt: "eggs",
    number: 13,
  },
  {
    category: "proteins",
    name: "Milk",
    imageSrc: "/icons/milk.png",
    imageAlt: "milk",
    number: 14,
  },
  {
    category: "vegetables",
    name: "Peas",
    imageSrc: "/icons/peas.png",
    imageAlt: "peas",
    number: 15,
  },
  {
    category: "vegetables",
    name: "Mushroom",
    imageSrc: "/icons/mushroom.png",
    imageAlt: "mushroom",
    number: 16,
  },
  {
    category: "vegetables",
    name: "Potato",
    imageSrc: "/icons/potato.png",
    imageAlt: "potato",
    number: 17,
  },
  {
    category: "vegetables",
    name: "Cucumber",
    imageSrc: "/icons/cucumber.png",
    imageAlt: "cucumber",
    number: 18,
  },
  {
    category: "vegetables",
    name: "Lettuce",
    imageSrc: "/icons/lettuce.png",
    imageAlt: "lettuce",
    number: 19,
  },
  {
    category: "seafood",
    name: "Cod",
    imageSrc: "/icons/cod.png",
    imageAlt: "cod",
    number: 20,
  },
  {
    category: "seafood",
    name: "Salmon",
    imageSrc: "/icons/salmon.png",
    imageAlt: "salmon",
    number: 21,
  },
  {
    category: "seafood",
    name: "Sardine",
    imageSrc: "/icons/sardines.png",
    imageAlt: "sardine",
    number: 22,
  },
  {
    category: "seafood",
    name: "Trout",
    imageSrc: "/icons/trout.png",
    imageAlt: "trout",
    number: 23,
  },
  {
    category: "seafood",
    name: "Tuna",
    imageSrc: "/icons/tuna.png",
    imageAlt: "tuna",
    number: 24,
  },
];

export const cardListRight = [
  {
    category: "fruit",
    name: "Cherries",
    imageSrc: "/icons/cherries.png",
    imageAlt: "cherries",
    number: 25,
  },
  {
    category: "fruit",
    name: "Grapes",
    imageSrc: "/icons/grapes.png",
    imageAlt: "grapes",
    number: 26,
  },
  {
    category: "fruit",
    name: "Pineapples",
    imageSrc: "/icons/pineapple.png",
    imageAlt: "pineapples",
    number: 27,
  },
  {
    category: "fruit",
    name: "Blackberries",
    imageSrc: "/icons/blackberry.png",
    imageAlt: "blackberries",
    number: 28,
  },
  {
    category: "fruit",
    name: "Blueberries",
    imageSrc: "/icons/blueberries.png",
    imageAlt: "blueberries",
    number: 29,
  },
  {
    category: "grain",
    name: "Pasta",
    imageSrc: "/icons/pasta.png",
    imageAlt: "pasta",
    number: 30,
  },
  {
    category: "grain",
    name: "Rice",
    imageSrc: "/icons/rice.png",
    imageAlt: "rice",
    number: 31,
  },
  {
    category: "proteins",
    name: "Pork",
    imageSrc: "/icons/pork.png",
    imageAlt: "pork",
    number: 32,
  },
  {
    category: "proteins",
    name: "Chicken",
    imageSrc: "/icons/chicken.png",
    imageAlt: "chicken",
    number: 33,
  },
  {
    category: "vegetables",
    name: "Tomato",
    imageSrc: "/icons/tomato.png",
    imageAlt: "tomato",
    number: 34,
  },
  {
    category: "vegetables",
    name: "Carrot",
    imageSrc: "/icons/carrot.png",
    imageAlt: "carrot",
    number: 35,
  },
  {
    category: "seafood",
    name: "Squid",
    imageSrc: "/icons/squid.png",
    imageAlt: "squid",
    number: 36,
  },
  {
    category: "seafood",
    name: "Prawn",
    imageSrc: "/icons/prawn.png",
    imageAlt: "prawn",
    number: 37,
  },
];
